import React, { useState } from 'react';
import { Button, Modal } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Link } from 'react-router-dom';

const ReportButton: React.FC = () => {
  const [showModal, setShowModal] = useState(false);

  return (
    <div>
      <div className="container">
        <div className="row">
          <div className="col-9" style={{ padding: '0 0 0 450px' }}>
            <Button
              variant="outline-primary"
              type="button"
              style={{
                backgroundColor: 'white',
                borderColor: '#331c7a',
                color: '#331c7a',
              }}
              onClick={() => setShowModal(true)} // Show modal when export to excel button is clicked
            >
              Export to Excel
            </Button>
          </div>
          <div className="col-3" style={{ padding: '0 0 0 0' }}>
            <Link to="/ReportHistory">
              <Button
                variant="outline-primary"
                type="button"
                style={{
                  backgroundColor: 'white',
                  borderColor: '#482890',
                  color: '#482890',
                }}
              >
                Report History
              </Button>
            </Link>
          </div>
        </div>
      </div>

      {/* Modal for export to excel */}
      <Modal show={showModal} onHide={() => setShowModal(false)}>
        <Modal.Header closeButton>
          <Modal.Title>Export to Excel</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <form>
            <div className="form-group">
              <label htmlFor="reportName">Report Name:</label>
              <input type="text" className="form-control" id="reportName" />
            </div>
            <div className="form-group">
              <label htmlFor="reportType">Report Type:</label>
              <input type="text" className="form-control" id="reportType" />
            </div>
            <div className="form-group">
              <label htmlFor="reportFormat">Report Format:</label>
              <input type="text" className="form-control" id="reportFormat" />
            </div>
            <div className="form-group">
              <label htmlFor="generatedBy">Generated By:</label>
              <input type="text" className="form-control" id="generatedBy" />
            </div>
            <div className="form-group">
              <label htmlFor="note">Note:</label>
              <textarea className="form-control" id="note" rows={3}></textarea>
            </div>
          </form>
        </Modal.Body>
        <Modal.Footer>
          
          <Button variant="primary" onClick={() => console.log('Export clicked')}>
           Submit
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
};

export default ReportButton;
